### PR TITLE
Erlang distribution

### PR DESCRIPTION
**Pull request by ellessenne**
Hi,
This PR adds support for the [Erlang distribution](https://en.wikipedia.org/wiki/Erlang_distribution); I implemented the `print`, `pdf`, `log_pdf`, `random`, `cdf`, and `quantile` methods.
Let me know if there's anything I need to change before this could be merged.
Thanks,

Alessandro

### CODE REVIEW

**Comment by alexpghayes** [comment]
Would you mind quickly merging in master to handle merge conflicts, then I'll merge the PR and do some cleanup?

**Comment by ellessenne** [comment]
Yep sure!

**Comment by alexpghayes** [comment]
Are you still interested in this? I have some maintainer time and can review if you get the PR to pass to checks. Otherwise will close shortly.

**Comment by ellessenne** [comment]
Hi @alexpghayes, happy to fix this if you can give me a few days to sort it out 😄 thanks!

**Comment by alexpghayes** [comment]
Great, I'll handle those. Thanks for reviving this!

**Comment by ellessenne** [comment]
No worries, thank you actually! 👍

**Pull request merged**
