### PR TITLE
Plot generic

### PR DESCRIPTION
**Pull request by paulnorthrop**
This PR relates to issue #9.  I am suggesting a simple plotting generic, plot.distribution(), that plots either the pmf/pdf or cdf of a univariate distribution.  It accommodates cases where vector parameters were passed to the function that created the distribution object (as noted in the discussion of issue #38).  In such cases a the required function is plotted for every combination of parameters.

The plotting generic works for any of the distributions currently available in distributions3.  However, currently this requires a manual check inside plot.distribution() that determines whether the distribution is discrete or continuous.  It may be better either to store lists of discrete and continuous distributions elsewhere in distribtions3 or perhaps to include this information in the class of distributions3 objects.

I am happy to amend plot.distribution() as necessary and I won't be offended if you want to approach this is a different way: I find this function useful for my own purposes, so would not have wasted any effort.

### CODE REVIEW

**Comment by alexpghayes** [comment]
Hey! I'm sorry I haven't respond to you! I'm currently in a finals crunch for the next two weeks. I will do my best to get back to you at the end of that period!

**Comment by paulnorthrop** [comment]
There's absolutely no need to apologise!  I expected that you would only be able to deal with PRs periodically.   Thank you for creating this package.  I'm already using it in my teaching: it's nice to be able to show my students a neat, intuitive and simple way to perform calculations based on the probability distributions that they encounter.  I hope that your finals go well.

**Comment by rmtrane** [comment]
@paulnorthrop Seems we both found this useful, and both implemented it, although in different ways. See #51 for my implementation. I went the ggplot2 route. 

Just wanted to bring this up, as I'll be using this package for teaching this semester, and find the lack of an easy way to plot cdf's frustrating. I have a solution to the problem, but thought going forward, it would be super useful if either method would make it into the package!

**Comment by paulnorthrop** [comment]
@rmtrane Many thanks for this.  I'll merge #51 in a moment.

**Pull request merged**
