### PR TITLE
Generic methods for the moments of a distribution 

### PR DESCRIPTION
**Pull request by 1danjordan**
This is the fixed branch from #32 - the contents is the same. The points to note/discuss are:

Firstly, mean is already a generic, which is fine but makes it awkward to create documentation for. I'm sure there is a work around for documenting a method when the generic is defined in your own package, but I'm not sure how to do it. Any thoughts?

Secondly, stats::var already claims the var function, so I opted for variance as the name of our generic - I think that's a reasonable compromise?

For distributions with undefined moments (e.g. Cauchy), I'm returning NaN, this makes the most sense. 

Finally, I'm planning on putting the documentation in one page, I don't see the need for individual man pages for each generic or method.

I'll finish off the other distributions in the next few days, so no need to merge yet. Just wanted to start the discussion early.

### CODE REVIEW

**Comment by rmtrane** [comment]
This is really awesome! Was thinking about implementing this myself, but you beat me to it. 

I want to throw an idea out there: use `E` instead of `mean` for the expected value. This would match 'blackboard notation' really nicely: a blackboard statement like "Let $X \sim N(2, 2^2)$. Then $E(X) = \mu$" would translate to `X <- Normal(0, 2); E(X)`. Seeing as one of the major strengths of this package, if you ask me, is that it bridges the gap between how we work with random variables/distributions in `R`, and how it is done in a more theoretical setting, I think adopting `E` for the expected value would be really neat. I also think this would be awesome for teaching, especially teaching intro stats classes using `R`. Thoughts?

I'm sure there are downsides that I haven't thought of, so please shoot down this idea if need be. 

Again, really love to see that this is being implemented as well.

**Comment by alexpghayes** [comment]
The E(X) notion idea is interesting. It suggests that E(X^k) should
calculate the kth moment. We could make this happen either with NSE or by
defining ^ as an infix(distribution, integer) operator.

**Comment by 1danjordan** [comment]
I'll be getting back to this work in the next few days. Summer holidays caught up with me. I like the idea of including an `E(X)` function. I'll pull a prototype together. @alexpghayes do you mind including `tidyeval` as a dependency?

**Comment by alexpghayes** [comment]
Do you mean rlang or something else?

**Comment by 1danjordan** [comment]
Sorry yes I meant `rlang`

**Comment by alexpghayes** [comment]
Yep, go wild!

**Comment by alexpghayes** [comment]
Thinking about this more. Options include:

1. Using `E(X^k)` notation. I'm... both nervous and excited about this.
2. Overwriting `mean()` with a generic that we export anyway so we can document or own generic.
3. Implementing `mean.Normal()`, etc, methods, but having these just be pointers to `E.Normal()` methods.

Another thought: we need to think about the `E` notation some more. What does `E(X - mu)` do? What about `E(X - E(X))`? If we allow `E(X^k)` people may expect other similar notation to work.

In any case, I see moments as some for version 0.2.0 rather than 0.1.0

**Comment by 1danjordan** [comment]
Just want to let you guys know that I'm still planning on finishing this pull request in the next while. I started a new job a few months back so this took a back seat for a while.

**Comment by 1danjordan** [comment]
This completes `mean`, `variance`, `skewness` and `kurtosis` for 24 distributions. I used Wikipedia and Distributions.jl as source and hope everything is correct. 

There are only tests written for a handful, because it was becoming incredibly tedious to write them. However, I found a possible solution which is to use the testing reference file that Distributions.jl use for their testing. I think that will probably be in another pull request as this one took me long enough (9 months 😱)!

**Comment by alexpghayes** [comment]
Thanks for making this happen! Let's revisit the testing strategy when we get a moment!

**Comment by 1danjordan** [comment]
Thanks for merging!

**Pull request merged**
