### PR TITLE
Pareto distribution

### PR DESCRIPTION
**Pull request by paulnorthrop**
This PR adds support for the (Type I) Pareto distribution: `cdf`, `log_pdf`, `pdf`, `print`, `quantile`, `random`, `suff_stats` and `fit_mle` methods.

Of course, I'm happy to make changes before merging if that's helpful.

Many thanks, Paul

### CODE REVIEW

**Comment by alexpghayes** [comment]
Hey I'm sorry that I haven't gotten to your PRs -- I don't have much time for this project at the moment. Would you be interested in acting as primary maintainer for `distributions3` and driving development forward? Mostly this would mean write access to this repo so you could iterate faster!

**Comment by paulnorthrop** [comment]
Hi Alex, I'm sorry for being slow to reply too!  If you are still interested in me acting as primary maintainer then, yes, I would would be happy to.

**Comment by alexpghayes** [comment]
Just gave you write access! I trust your judgement!

**Comment by alexpghayes** [comment]
Would you mind quickly merging in master to handle merge conflicts, then I'll merge the PR and do some cleanup?

**Comment by alexpghayes** [comment]
Are you still interested in this? I have some maintainer time and can review if you get the PR to pass to checks. Otherwise will close shortly.

**Pull request closed without merging**
