### PR TITLE
Adding error handling for non-integer input to pdf for discrete distributions

### PR DESCRIPTION
**Pull request by EmilHvitfeldt**
Quick and dirty before and after photo

Screen Shot 2019-06-27 at 6 04 21 PM

### CODE REVIEW

**Comment by alexpghayes** [comment]
I've been thinking about this and I don't think erroring is the right approach here. I think we should return zero from `pdf()` and `cdf()` when the input is outside the support of the distribution. Otherwise math code has to start error handling, which really is nasty in R and also not a well known skill. I think we'd then need to clear documentation on "What do when you keep getting zero and don't know why". Thoughts?

**Comment by EmilHvitfeldt** [comment]
What about we return zeroes and give informative error messages? it can be hard to see the difference between a low value `pdf(Normal(), 10000)` and an impossible value `pdf(Bernoulli(), 0.5)`

**Comment by 1danjordan** [comment]
The correct thing is to return `0`. Raising an error would be mathematically inconsistent and reek havoc in non-interactive programs. But I think there is something in an informative message. In most cases of people are mistaken about the domain of the distribution (putting continuous values into a discrete distribution) rather than actually interested in the probability of some impossible value.

**Comment by EmilHvitfeldt** [comment]
Okay what do you think about this solution? A warning is given with reason, and zeroes are returned, matching the dimensions of `x`.

``` r
library(distributions)
p <- Poisson(1)
pdf(p, rnorm(10))
#> Warning in pdf.Poisson(p, rnorm(10)): `x` must be an integer, since the support of Poisson is in the integers.
#>  [1] 0 0 0 0 0 0 0 0 0 0

pdf(p, matrix(rnorm(100), 10, 10))
#> Warning in pdf.Poisson(p, matrix(rnorm(100), 10, 10)): `x` must be an integer, since the support of Poisson is in the integers.
#>       [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
#>  [1,]    0    0    0    0    0    0    0    0    0     0
#>  [2,]    0    0    0    0    0    0    0    0    0     0
#>  [3,]    0    0    0    0    0    0    0    0    0     0
#>  [4,]    0    0    0    0    0    0    0    0    0     0
#>  [5,]    0    0    0    0    0    0    0    0    0     0
#>  [6,]    0    0    0    0    0    0    0    0    0     0
#>  [7,]    0    0    0    0    0    0    0    0    0     0
#>  [8,]    0    0    0    0    0    0    0    0    0     0
#>  [9,]    0    0    0    0    0    0    0    0    0     0
#> [10,]    0    0    0    0    0    0    0    0    0     0

pdf(p, array(rnorm(8), c(2, 2, 2)))
#> Warning in pdf.Poisson(p, array(rnorm(8), c(2, 2, 2))): `x` must be an integer, since the support of Poisson is in the integers.
#> , , 1
#> 
#>      [,1] [,2]
#> [1,]    0    0
#> [2,]    0    0
#> 
#> , , 2
#> 
#>      [,1] [,2]
#> [1,]    0    0
#> [2,]    0    0
```

<sup>Created on 2019-06-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by rmtrane** [comment]
I believe the pdf of an element not in the support return 0, but the cdf for a discrete random variable is well-defined as a right-continuous step function. `cdf(Poisson(), 2.2)` should return the same result as `cdf(Poisson(), 2)`, no? In general, for discrete random variables with integer support, `cdf(X, x) = cdf(X, floor(x))`.

**Comment by 1danjordan** [comment]
Yep agreed

**Comment by alexpghayes** [comment]
I'm not sure I feel about a warning tbh. I think people are going to be surprised by getting a zero not because it is a surprising behavior, but mostly because they haven't seen enough stats to know that pdfs are implicitly zero outside the support of the distribution. Here's where I'm currently at:

- The documentation for each distribution should make it clear that the pdf is zero outside the support of the distribution
- I'd be okay with a global `option(distributions::warn_on_inputs_outside_support = FALSE)`, although preferably with better naming. Then `pdf()` methods can have some input validator that checks the option and possibly warns.

**Comment by alexpghayes** [comment]
Also, we probably should come up with a better way to represent the support of a distribution.

**Comment by alexpghayes** [comment]
Closing this for the time being. https://github.com/xoopR/set6 is a possible way to represent supports, although we could probably do something way more stripped down (and not R6, which might be a confusing mix) internally.

**Pull request closed without merging**
