### PR TITLE
Export and improve apply_dpqr (and other helper functions)

### PR DESCRIPTION
**Pull request by zeileis**
**Main changes:**

In order to facilitate writing new distributions, it would be nice to export the new helper functions `apply_dpqr()`, `make_support()`, and `make_positive_integer()`. Especially when including such distributions in other packages, e.g., because the `d`/`p`/`q`/`r` functions reside there, it would be necessary to export the functions because otherwise they may not be accessed.

This PR makes these exports and improves the `apply_dpqr()` function, especially for the `random()` methods. Now the computations are much faster when drawing large random samples for a distribution object with possibly a large number of different distributions. This is achieved by using `replicate()` instead of `vapply()` for drawing random samples.

To facilitate use of the helper functions the accompanying manual page includes a worked illustration for setting up a new distribution along with the most important methods.

**Furthermore:**

* Adapt all `random()` methods to properly use the improved `apply_dpqr()`.
* Adapt all tests accordingly.
* For `drop = TRUE` an unnamed vector is now returned; hence, we export column names only if the dimension is not dropped.
* Streamlining of `make_suffix()` using the faster `format()` instead of the slower `sapply()`.

### CODE REVIEW

**Comment by zeileis** [comment]
Hi Alex @alexpghayes, it seems that the Mac OS check timed out, not sure why. If there is anything we should do to address this, let us know.

**Comment by alexpghayes** [comment]
Looks good to me! Thanks!

**Comment by alexpghayes** [comment]
Great, just let me know what you need!

**Comment by zeileis** [comment]
Perfect, thanks!!

**Pull request merged**
