### PR TITLE
Added a few functions + fixed a few mistakes

### PR DESCRIPTION
**Pull request by rmtrane**
* Added functions to return the support of distribution objects
* Added functions `plot_cdf` and `plot_pdf` to plot cdf and pdf of a distribution object using the support to define the default range. 
* Includes fix to #49 and #50 #

### CODE REVIEW

**Comment by EmilHvitfeldt** [comment]
heads up, It appears you deleted the man/ folder :)

**Comment by rmtrane** [comment]
> heads up, It appears you deleted the man/ folder :)

Oops.. Thanks!

**Comment by alexpghayes** [comment]
I like where you're going with this, but have some thoughts. Probably easier to talk in person. Are you gonna be around MSC / the east side next week?

**Comment by rmtrane** [comment]
>I like where you're going with this, but have some thoughts. Probably easier to talk in person. Are you gonna be around MSC / the east side next week?

@alexpghayes Let’s chat next week, maybe Tuesday before causal. Mainly implemented this because I needed it for a Shiny app and thought it might add some value. Open to any and all suggestions/thoughts. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
