### PR TITLE
Bug-fix & extend negative binomial distribution

### PR DESCRIPTION
**Pull request by zeileis**
Alex @alexpghayes , as mentioned yesterday I have now extended the `NegativeBinomial()` distribution to allow the parameterization with `mu` and `size` (popular for regression modeling) in addition to the classic parameterization with `p` and `size`. The parameters `p` and `mu` can be mapped back and forth (given `size`): `p = size/(size + mu)` and `mu = (1 - p) * size/p`.

The main extensions are in the `NegativeBinomial()` constructor where either one or the other pair of parameters is stored after suitable consistency checks. All methods then check whether the parameter `mu` or `p` is available and then call the corresponding `d`/`p`/`q`/`r` `nbinom` functions with the available parameters.

The documentation was also extended with a paragraph on the alternative parameterization at the end. When doing so I noticed that the documentation was not in sync with the code. It claimed that the distribution counts successes until a target number of failures - but the `nbinom` functions in R actually count failures until a target number of successes. Thus, this corresponds to using `1 - p` instead of `p` and vice versa. I changed the documentation to be in line with the code now (and thus to be consistent with base R's documentation).

### CODE REVIEW

**Comment by alexpghayes** [comment]
Would you add a quick test that for the new parameterization? Otherwise looks good to me, and nice catch in the documentation.

**Comment by zeileis** [comment]
Just as a brief explanation: All of the test-_Distribution_.R files had the `Normal()` distribution in the last battery of checks (whether names are preserved). I have replaced all of these with the intended distributions and pushed my fix a bit prematurely. I still need to have a closer look at what goes wrong now.

When I have fixed these old tests, I will add the new tests for the alternative negbin parameterization and the new zero-augmented Poisson distributions.

More later...

**Comment by zeileis** [comment]
OK, so far so good:
* Mainly when replacing the `Normal()` with the intended distribution in test-_Distribution_.R I didn't pay attention that `pdf()` and `log_pdf()` need to get arguments from the correct support. Also, I sometimes had erroneously used a vector of three rather than just two distributions.
* Going through all of these tests I discoved a number of bugs in the package that I have fixed now.
* The `suff_stat()` generic was not exported (only the methods registered).
* In the `kurtosis()` method for `Gamma` distributions the `rval` was computed correctly but not returned.
* The `random()` method for `LogNormal` distributions had a small glitch and hence did not work.

On now with my actual task (adding tests for the new/extended count distributions), more soon.

**Comment by zeileis** [comment]
I think that this should be good to go now, Alex @alexpghayes ! Let me know if you spot anything else that needs to be done.

The added tests for the alternative `NegativeBinomial()` parameterization and the new `ZIPoisson()` and `HurdlePoisson()` were relatively straightforward and work all as intended. The fixes I did along the way were more work than expected but were all relevant and uncovered some glitches that could be fix. Code coverage is now back up above 95%.

**Comment by alexpghayes** [comment]
Wow thank you so much for this!

**Comment by zeileis** [comment]
Thanks! Next I will try to do the `ZINegativeBinomial()` and `HurdleNegativeBinomial()` functionality.

**Pull request merged**
